import type { ArrivalChecklistItem } from './types.js';

export const ARRIVAL_CHECKLIST_SEED: ArrivalChecklistItem[] = [
  {
    id: 'kul-immigration-mdac',
    airportCode: 'KUL',
    stage: 'immigration',
    title: 'Complete MDAC before passport control',
    body: 'Fill the Malaysia Digital Arrival Card (MDAC) online before you reach KLIA immigration. Have your passport, flight number, and Malaysian address ready. Follow signs for Arrivals / Immigration after leaving the aircraft.',
    sortOrder: 1,
    estimatedMinutes: 10,
  },
  {
    id: 'kul-immigration-counters',
    airportCode: 'KUL',
    stage: 'immigration',
    title: 'Passport control at KLIA (main)',
    body: 'Join the foreign-passport queues unless you hold a Malaysian passport. Keep boarding pass and hotel address handy. Automated gates may be available for eligible passports; otherwise use a manned counter.',
    sortOrder: 2,
    estimatedMinutes: 20,
  },
  {
    id: 'kul-baggage-carousel',
    airportCode: 'KUL',
    stage: 'baggage',
    title: 'Collect bags at the KLIA carousel',
    body: 'After immigration, follow Baggage Reclaim. Check screens for your flight number and carousel. Trolleys are free in the reclaim hall.',
    sortOrder: 1,
    estimatedMinutes: 25,
  },
  {
    id: 'kul-baggage-lost',
    airportCode: 'KUL',
    stage: 'baggage',
    title: 'Report missing luggage',
    body: 'If your bag does not appear, go to the airline’s baggage services desk in the reclaim hall with your baggage tag and passport before leaving customs.',
    sortOrder: 2,
    estimatedMinutes: 15,
  },
  {
    id: 'kul-customs-green-red',
    airportCode: 'KUL',
    stage: 'customs',
    title: 'Choose Green or Red Channel',
    body: 'Use the Green Channel if you have nothing to declare. Use Red if you carry dutiable goods, large amounts of cash, or restricted items. Keep receipts for new electronics if asked.',
    sortOrder: 1,
    estimatedMinutes: 10,
  },
  {
    id: 'kul-sim-counters',
    airportCode: 'KUL',
    stage: 'sim',
    title: 'Buy a local SIM or eSIM after customs',
    body: 'Prepaid SIM and eSIM counters (CelcomDigi, Maxis, U Mobile, and kiosks) sit in the public arrivals hall after customs. Passport is required. eSIM can also be installed before you fly if you already purchased one.',
    sortOrder: 1,
    estimatedMinutes: 15,
  },
  {
    id: 'kul-money-atm',
    airportCode: 'KUL',
    stage: 'money',
    title: 'Withdraw ringgit or exchange a little cash',
    body: 'ATMs and licensed money changers are in the KLIA arrivals hall. Withdraw a small amount of MYR for taxis or snacks; cards are widely accepted in the city. Compare rates before exchanging large sums.',
    sortOrder: 1,
    estimatedMinutes: 10,
  },
  {
    id: 'kul-transport-ekspres',
    airportCode: 'KUL',
    stage: 'transport',
    title: 'KLIA Ekspres, bus, Grab, or taxi',
    body: 'KLIA Ekspres trains run from KLIA to KL Sentral (about 28 minutes). Buses and licensed airport taxis leave from the ground-transport level. Grab pickup is signed in the arrivals forecourt—confirm the pin in the app before you walk out.',
    sortOrder: 1,
    estimatedMinutes: 40,
  },
  {
    id: 'kul-first-steps-hotel',
    airportCode: 'KUL',
    stage: 'first_steps',
    title: 'Settle in: hotel, water, and emergency numbers',
    body: 'Confirm your hotel address in Grab or with the taxi desk. Tap water is not always recommended for visitors—buy bottled water. Save 999 for police/ambulance/fire and 03-2115 9999 for tourist police. Turn on mobile data once your SIM is active.',
    sortOrder: 1,
    estimatedMinutes: 15,
  },
  {
    id: 'klia2-immigration-mdac',
    airportCode: 'KLIA2',
    stage: 'immigration',
    title: 'Complete MDAC, then KLIA2 immigration',
    body: 'Submit MDAC before landing if required. At KLIA2, follow Arrivals down to immigration. Low-cost terminals can be busy after evening AirAsia banks—keep passport and MDAC confirmation ready.',
    sortOrder: 1,
    estimatedMinutes: 15,
  },
  {
    id: 'klia2-immigration-counters',
    airportCode: 'KLIA2',
    stage: 'immigration',
    title: 'Passport control at KLIA2',
    body: 'Use foreign-visitor lanes. After stamping, continue to baggage reclaim on the same level. Do not exit toward landside until you have cleared customs.',
    sortOrder: 2,
    estimatedMinutes: 25,
  },
  {
    id: 'klia2-baggage-carousel',
    airportCode: 'KLIA2',
    stage: 'baggage',
    title: 'Find your KLIA2 carousel',
    body: 'Belt numbers are shown on screens in the KLIA2 reclaim hall. The hall is compact compared with main KLIA; trolleys are available near the belts.',
    sortOrder: 1,
    estimatedMinutes: 20,
  },
  {
    id: 'klia2-baggage-lost',
    airportCode: 'KLIA2',
    stage: 'baggage',
    title: 'Airline baggage desk at KLIA2',
    body: 'Missing bag? Go to your airline’s desk (often AirAsia) in reclaim before customs. Photograph your baggage tag and keep boarding details.',
    sortOrder: 2,
    estimatedMinutes: 15,
  },
  {
    id: 'klia2-customs-channel',
    airportCode: 'KLIA2',
    stage: 'customs',
    title: 'Clear KLIA2 customs',
    body: 'Walk through Green Channel with nothing to declare, or Red Channel for goods and large cash. You exit into the KLIA2 Gateway public hall.',
    sortOrder: 1,
    estimatedMinutes: 10,
  },
  {
    id: 'klia2-sim-gateway',
    airportCode: 'KLIA2',
    stage: 'sim',
    title: 'SIM and eSIM in Gateway@klia2',
    body: 'After customs, SIM counters cluster in the Gateway mall / arrivals area. Compare prepaid tourist packs. Passport needed for registration. Wi-Fi is available while you wait.',
    sortOrder: 1,
    estimatedMinutes: 15,
  },
  {
    id: 'klia2-money-atm',
    airportCode: 'KLIA2',
    stage: 'money',
    title: 'ATMs and changers in Gateway',
    body: 'ATMs and money changers sit in Gateway@klia2 after you leave customs. Withdraw MYR for the train or bus. Avoid unofficial changers outside the terminal.',
    sortOrder: 1,
    estimatedMinutes: 10,
  },
  {
    id: 'klia2-transport-options',
    airportCode: 'KLIA2',
    stage: 'transport',
    title: 'KLIA Ekspres from KLIA2, bus, Grab, taxi',
    body: 'KLIA Ekspres and KLIA Transit stop at KLIA2 (Gateway). Follow signs upstairs to the station. Buses use the transportation hub; Grab pickup points are marked on the kerbside—do not follow touts.',
    sortOrder: 1,
    estimatedMinutes: 45,
  },
  {
    id: 'klia2-first-steps',
    airportCode: 'KLIA2',
    stage: 'first_steps',
    title: 'Hotel, water, data, emergencies',
    body: 'Share the KLIA2 pin with your driver (it is a different terminal from main KLIA). Buy water in Gateway. Enable data, and save 999 plus tourist police 03-2115 9999.',
    sortOrder: 1,
    estimatedMinutes: 15,
  },
];
