import type { ArrivalTransportOption } from './types.js';

export const ARRIVAL_TRANSPORT_SEED: ArrivalTransportOption[] = [
  {
    id: 'kul-opt-ekspres',
    airportCode: 'KUL',
    mode: 'ekspres',
    name: 'KLIA Ekspres',
    badge: 'Fastest',
    summary: 'Direct non-stop high-speed train to the city rail hub.',
    cost: '~RM 55 per adult',
    duration: '28 mins',
    frequency: 'Every 15–20 min',
    destination: 'KL Sentral',
    bestFor: 'Solo travelers, business visitors, bypassing highway traffic',
    boarding: 'KLIA (main) Level 1 station. Follow KLIA Ekspres signs after customs.',
    whenToUse:
      'Choose this when you want the most reliable timing, your hotel is near KL Sentral or on the LRT/MRT/Monorail, and you can handle bags on trains. Skip it for door-to-door hotel drop-off or late-night arrivals with heavy luggage.',
    sortOrder: 1,
  },
  {
    id: 'kul-opt-bus',
    airportCode: 'KUL',
    mode: 'bus',
    name: 'Airport bus',
    badge: 'Budget',
    summary: 'Aerobus / Jetbus coaches from the transportation hub.',
    cost: '~RM 12–15 per seat',
    duration: '60–75 mins',
    frequency: 'About every 30 min',
    destination: 'KL Sentral (and some hotel routes)',
    bestFor: 'Backpackers and budget trips into the city hub',
    boarding: 'Ground-floor transportation hub at KLIA (main). Buy tickets at official counters only.',
    whenToUse:
      'Use buses when cost matters more than speed and you are heading to KL Sentral with light bags. Avoid if you have a tight check-in, several large suitcases, young children, or a hotel far from Sentral.',
    sortOrder: 2,
  },
  {
    id: 'kul-opt-e-hail',
    airportCode: 'KUL',
    mode: 'e_hail',
    name: 'Grab / taxi',
    badge: 'Door-to-door',
    summary: 'Official e-hailing (Grab, AirAsia Ride) or prepaid coupon taxis.',
    cost: '~RM 65–85 + ~RM 8 toll',
    duration: '50–65 mins',
    destination: 'Direct to hotel',
    bestFor: 'Families, groups of 2–4, multiple large suitcases',
    boarding:
      'Grab: KLIA Level 1 Doors 3 & 4 (confirm the in-app pin). Coupon taxis: prepaid booths inside the terminal—never follow touts in the hall.',
    whenToUse:
      'Best when you need a hotel drop-off, have lots of luggage, or travel as a small group that can split the fare. Use the app or an official taxi booth. Skip random drivers in arrivals. If you have no data yet, buy a SIM first or use a coupon taxi counter.',
    sortOrder: 3,
  },
  {
    id: 'kul-opt-private',
    airportCode: 'KUL',
    mode: 'private',
    name: 'Private transfer',
    badge: 'Meet & greet',
    summary: 'Pre-booked car with a named driver waiting landside.',
    cost: 'Higher fixed quote (often RM 150+)',
    duration: '50–70 mins',
    destination: 'Direct to hotel or address',
    bestFor: 'Late flights, large groups, mobility needs, first-time visitors',
    boarding: 'Meet at the signed arrivals meeting point after customs. Confirm KLIA (main), not KLIA2.',
    whenToUse:
      'Book ahead when you want a driver holding your name after a long-haul or overnight flight, you have mobility or family needs, or your stay is not convenient from KL Sentral. Confirm the terminal in the booking. Overkill if you are solo, traveling light, and heading to a Sentral-area hotel.',
    sortOrder: 4,
  },
  {
    id: 'klia2-opt-ekspres',
    airportCode: 'KLIA2',
    mode: 'ekspres',
    name: 'KLIA Ekspres',
    badge: 'Fastest',
    summary: 'KLIA Ekspres and KLIA Transit from Gateway@klia2.',
    cost: '~RM 55 per adult',
    duration: '33 mins',
    frequency: 'Every 15–20 min',
    destination: 'KL Sentral (via KLIA Transit stops if you choose Transit)',
    bestFor: 'Solo and business travelers avoiding highway traffic',
    boarding: 'Follow signs upstairs to the station at Gateway@klia2 Level 2.',
    whenToUse:
      'Pick the train when you want a fixed 30-ish minute ride to KL Sentral and can manage bags. KLIA Transit is slower but useful if you need intermediate stops. Not ideal as a door-to-door hotel ride.',
    sortOrder: 1,
  },
  {
    id: 'klia2-opt-bus',
    airportCode: 'KLIA2',
    mode: 'bus',
    name: 'Airport bus',
    badge: 'Budget',
    summary: 'Coaches from the KLIA2 transportation hub.',
    cost: '~RM 12–15 per seat',
    duration: '60–80 mins',
    frequency: 'About every 30 min',
    destination: 'KL Sentral',
    bestFor: 'Budget travelers going into the city hub',
    boarding: 'Transportation hub at KLIA2. Official Aerobus / Jetbus counters only.',
    whenToUse:
      'Good for a cheap ride to KL Sentral with a backpack. Poor fit for late-night AirAsia banks with queues, bulky luggage, or hotels that still need a second taxi from Sentral.',
    sortOrder: 2,
  },
  {
    id: 'klia2-opt-e-hail',
    airportCode: 'KLIA2',
    mode: 'e_hail',
    name: 'Grab / taxi',
    badge: 'Door-to-door',
    summary: 'Grab, AirAsia Ride, or licensed coupon taxis from KLIA2.',
    cost: '~RM 65–90 + toll',
    duration: '50–70 mins',
    destination: 'Direct to hotel',
    bestFor: 'Families, groups, and travelers with several bags',
    boarding:
      'Grab pickup is marked on the kerbside (often Level 1 Door 5)—set the pin to KLIA2, not main KLIA. Coupon taxis use indoor booths. Ignore touts.',
    whenToUse:
      'Use this for a hotel drop-off from the low-cost terminal, especially with bags. Double-check the terminal in the app. Coupon taxis help if you do not have mobile data yet.',
    sortOrder: 3,
  },
  {
    id: 'klia2-opt-private',
    airportCode: 'KLIA2',
    mode: 'private',
    name: 'Private transfer',
    badge: 'Meet & greet',
    summary: 'Pre-booked driver waiting in the Gateway public hall.',
    cost: 'Higher fixed quote (often RM 150+)',
    duration: '50–75 mins',
    destination: 'Direct to hotel or address',
    bestFor: 'Overnight arrivals, groups, and limited-mobility travelers',
    boarding: 'Gateway@klia2 arrivals meeting point. The booking must say KLIA2, not KLIA main.',
    whenToUse:
      'Worth it after late AirAsia arrivals, with kids, or if walking to bus/train platforms is difficult. Confirm KLIA2 in writing so the driver does not wait at the main terminal.',
    sortOrder: 4,
  },
];
