import { isOfficialMissionWebsite, type ForeignMission, type MalaysiaEmbassySeed } from './types.js';

const CONSULAR_HOURS =
  'Confirm consular hours and appointments on the official website; many missions are by appointment only.';

const WHEN_TO_USE =
  'Use after a police report for a lost or stolen passport, or for consular help from this mission. Confirm hours on the official website. This is not 999 / SOS and is not visa or immigration advice.';

function mission(
  partial: Omit<ForeignMission, 'city' | 'area' | 'hours' | 'sourceUrl' | 'whenToUse'> & {
    area?: string;
    hours?: string;
    whenToUse?: string;
  },
): ForeignMission {
  if (!isOfficialMissionWebsite(partial.officialWebsite)) {
    throw new Error(`Unofficial or invalid mission website: ${partial.officialWebsite}`);
  }
  return {
    ...partial,
    city: 'Kuala Lumpur',
    area: partial.area ?? 'Kuala Lumpur',
    hours: partial.hours ?? CONSULAR_HOURS,
    whenToUse: partial.whenToUse ?? WHEN_TO_USE,
    sourceUrl: partial.officialWebsite,
  };
}

export const MALAYSIA_EMBASSY_MISSIONS: ForeignMission[] = [
  mission({
    id: 'kl-mission-au',
    name: 'Australian High Commission',
    sendingCountry: 'Australia',
    sendingCountryCode: 'AU',
    kind: 'high_commission',
    address: '6 Jalan Yap Kwan Seng, 50450 Kuala Lumpur',
    officialWebsite: 'https://malaysia.embassy.gov.au/',
    summary: 'Australian High Commission in Kuala Lumpur for consular assistance to Australian nationals.',
    tags: ['australia', 'aussie', 'high commission', 'consulate', 'consular', 'passport'],
    source: 'Australian High Commission, Malaysia',
    sortOrder: 1,
  }),
  mission({
    id: 'kl-mission-ca',
    name: 'High Commission of Canada',
    sendingCountry: 'Canada',
    sendingCountryCode: 'CA',
    kind: 'high_commission',
    address: '17th Floor, Menara Tan & Tan, 207 Jalan Tun Razak, 50400 Kuala Lumpur',
    officialWebsite:
      'https://www.international.gc.ca/country-pays/malaysia-malaisie/kuala_lumpur.aspx?lang=eng',
    summary: 'High Commission of Canada in Kuala Lumpur for consular assistance to Canadian nationals.',
    tags: ['canada', 'canadian', 'high commission', 'consulate', 'consular', 'passport'],
    source: 'High Commission of Canada in Malaysia',
    sortOrder: 2,
  }),
  mission({
    id: 'kl-mission-cn',
    name: "Embassy of the People's Republic of China",
    sendingCountry: 'China',
    sendingCountryCode: 'CN',
    kind: 'embassy',
    officialWebsite: 'https://my.china-embassy.gov.cn/eng/',
    summary: 'Chinese Embassy in Kuala Lumpur for consular assistance to Chinese nationals.',
    tags: ['china', 'chinese', 'prc', 'embassy', 'consulate', 'consular', 'passport'],
    source: "Embassy of the People's Republic of China in Malaysia",
    sortOrder: 3,
  }),
  mission({
    id: 'kl-mission-fr',
    name: 'Embassy of France',
    sendingCountry: 'France',
    sendingCountryCode: 'FR',
    kind: 'embassy',
    officialWebsite: 'https://my.ambafrance.org/',
    summary: 'French Embassy in Malaysia for consular assistance to French nationals.',
    tags: ['france', 'french', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'Ambassade de France en Malaisie',
    sortOrder: 4,
  }),
  mission({
    id: 'kl-mission-de',
    name: 'Embassy of Germany',
    sendingCountry: 'Germany',
    sendingCountryCode: 'DE',
    kind: 'embassy',
    address: '26th Floor, Menara Tan & Tan, 207 Jalan Tun Razak, 50400 Kuala Lumpur',
    officialWebsite: 'https://kuala-lumpur.diplo.de/my-en',
    summary: 'German Embassy in Kuala Lumpur for consular assistance to German nationals.',
    tags: ['germany', 'german', 'deutschland', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'German Embassy Kuala Lumpur',
    sortOrder: 5,
  }),
  mission({
    id: 'kl-mission-in',
    name: 'High Commission of India',
    sendingCountry: 'India',
    sendingCountryCode: 'IN',
    kind: 'high_commission',
    address: 'Level 1, Wisma HRIH Lotus, 442 Jalan Pahang, Setapak, 53000 Kuala Lumpur',
    officialWebsite: 'https://www.hcikl.gov.in/',
    summary: 'High Commission of India in Kuala Lumpur for consular assistance to Indian nationals.',
    tags: ['india', 'indian', 'high commission', 'consulate', 'consular', 'passport'],
    source: 'High Commission of India, Kuala Lumpur',
    sortOrder: 6,
  }),
  mission({
    id: 'kl-mission-id',
    name: 'Embassy of Indonesia',
    sendingCountry: 'Indonesia',
    sendingCountryCode: 'ID',
    kind: 'embassy',
    address: '233 Jalan Tun Razak, 50400 Kuala Lumpur',
    officialWebsite: 'https://kemlu.go.id/kualalumpur/en',
    summary: 'Indonesian Embassy (KBRI) in Kuala Lumpur for consular assistance to Indonesian nationals.',
    tags: ['indonesia', 'indonesian', 'kbri', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'Kedutaan Besar Republik Indonesia Kuala Lumpur',
    sortOrder: 7,
  }),
  mission({
    id: 'kl-mission-ie',
    name: 'Embassy of Ireland',
    sendingCountry: 'Ireland',
    sendingCountryCode: 'IE',
    kind: 'embassy',
    address: 'South Block, 5th Floor, The Amp Walk, 218 Jalan Ampang, 50450 Kuala Lumpur',
    officialWebsite: 'https://www.ireland.ie/en/malaysia/kualalumpur/',
    summary: 'Embassy of Ireland in Malaysia for consular assistance to Irish nationals.',
    tags: ['ireland', 'irish', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'Embassy of Ireland, Malaysia',
    sortOrder: 8,
  }),
  mission({
    id: 'kl-mission-jp',
    name: 'Embassy of Japan',
    sendingCountry: 'Japan',
    sendingCountryCode: 'JP',
    kind: 'embassy',
    address: '11 Persiaran Stonor, Off Jalan Tun Razak, 50450 Kuala Lumpur',
    officialWebsite: 'https://www.my.emb-japan.go.jp/itprtop_en/index.html',
    summary: 'Embassy of Japan in Malaysia for consular assistance to Japanese nationals.',
    tags: ['japan', 'japanese', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'Embassy of Japan in Malaysia',
    sortOrder: 9,
  }),
  mission({
    id: 'kl-mission-nl',
    name: 'Embassy of the Netherlands',
    sendingCountry: 'Netherlands',
    sendingCountryCode: 'NL',
    kind: 'embassy',
    officialWebsite: 'https://www.netherlandsandyou.nl/web/malaysia',
    summary: 'Embassy of the Kingdom of the Netherlands in Malaysia for consular assistance to Dutch nationals.',
    tags: ['netherlands', 'dutch', 'holland', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'Embassy of the Kingdom of the Netherlands in Malaysia',
    sortOrder: 10,
  }),
  mission({
    id: 'kl-mission-nz',
    name: 'New Zealand High Commission',
    sendingCountry: 'New Zealand',
    sendingCountryCode: 'NZ',
    kind: 'high_commission',
    address: 'Level 8, Menara Hap Seng, 3 Jalan P Ramlee, 50250 Kuala Lumpur',
    officialWebsite: 'https://www.mfat.govt.nz/en/countries-and-regions/asia/malaysia/new-zealand-high-commission',
    summary: 'New Zealand High Commission in Kuala Lumpur for consular assistance to New Zealand nationals.',
    tags: ['new zealand', 'kiwi', 'nz', 'high commission', 'consulate', 'consular', 'passport'],
    source: 'New Zealand High Commission to Malaysia',
    sortOrder: 11,
  }),
  mission({
    id: 'kl-mission-ph',
    name: 'Embassy of the Philippines',
    sendingCountry: 'Philippines',
    sendingCountryCode: 'PH',
    kind: 'embassy',
    address: '1 Jalan Changkat Kia Peng, 50450 Kuala Lumpur',
    officialWebsite: 'https://kualalumpurpe.dfa.gov.ph/',
    summary: 'Philippine Embassy in Kuala Lumpur for consular assistance to Filipino nationals.',
    tags: ['philippines', 'filipino', 'pinoy', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'Philippine Embassy in Kuala Lumpur',
    sortOrder: 12,
  }),
  mission({
    id: 'kl-mission-sg',
    name: 'High Commission of the Republic of Singapore',
    sendingCountry: 'Singapore',
    sendingCountryCode: 'SG',
    kind: 'high_commission',
    officialWebsite: 'https://kl.mfa.gov.sg/',
    summary: 'Singapore High Commission in Kuala Lumpur for consular assistance to Singaporean nationals.',
    tags: ['singapore', 'singaporean', 'high commission', 'consulate', 'consular', 'passport'],
    source: 'High Commission of the Republic of Singapore in Kuala Lumpur',
    sortOrder: 13,
  }),
  mission({
    id: 'kl-mission-kr',
    name: 'Embassy of the Republic of Korea',
    sendingCountry: 'South Korea',
    sendingCountryCode: 'KR',
    kind: 'embassy',
    address: '9 & 11 Jalan Nipah, Off Jalan Ampang, 55000 Kuala Lumpur',
    officialWebsite: 'https://www.mofa.go.kr/my-en/index.do',
    summary: 'Embassy of the Republic of Korea in Malaysia for consular assistance to Korean nationals.',
    tags: ['korea', 'south korea', 'korean', 'rok', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'Embassy of the Republic of Korea in Malaysia',
    sortOrder: 14,
  }),
  mission({
    id: 'kl-mission-th',
    name: 'Royal Thai Embassy',
    sendingCountry: 'Thailand',
    sendingCountryCode: 'TH',
    kind: 'embassy',
    address: '206 Jalan Ampang, 50450 Kuala Lumpur',
    officialWebsite: 'https://kualalumpur.thaiembassy.org/',
    summary: 'Royal Thai Embassy in Kuala Lumpur for consular assistance to Thai nationals.',
    tags: ['thailand', 'thai', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'Royal Thai Embassy, Kuala Lumpur',
    sortOrder: 15,
  }),
  mission({
    id: 'kl-mission-gb',
    name: 'British High Commission',
    sendingCountry: 'United Kingdom',
    sendingCountryCode: 'GB',
    kind: 'high_commission',
    address: 'Level 27, Menara Binjai, 2 Jalan Binjai, 50450 Kuala Lumpur',
    officialWebsite: 'https://www.gov.uk/world/organisations/british-high-commission-kuala-lumpur',
    summary: 'British High Commission in Kuala Lumpur for consular assistance to British nationals.',
    tags: ['uk', 'united kingdom', 'britain', 'british', 'high commission', 'consulate', 'consular', 'passport'],
    source: 'British High Commission Kuala Lumpur',
    sortOrder: 16,
  }),
  mission({
    id: 'kl-mission-us',
    name: 'U.S. Embassy in Malaysia',
    sendingCountry: 'United States',
    sendingCountryCode: 'US',
    kind: 'embassy',
    address: '376 Jalan Tun Razak, 50400 Kuala Lumpur',
    officialWebsite: 'https://my.usembassy.gov/',
    summary: 'U.S. Embassy in Kuala Lumpur for consular assistance to U.S. nationals.',
    tags: ['united states', 'usa', 'america', 'american', 'embassy', 'consulate', 'consular', 'passport'],
    source: 'U.S. Embassy in Malaysia',
    sortOrder: 17,
  }),
];

export const MALAYSIA_EMBASSY_SEED: MalaysiaEmbassySeed = {
  country: 'MY',
  destination: 'Malaysia',
  version: '2026-09-mvp',
  disclaimer:
    'This is a seed of major foreign missions in Kuala Lumpur, not a complete list of every embassy or consulate in Malaysia. Contact links are official mission websites only. Confirm details on the site before you travel. If you are in immediate danger, call 999 or 112 — do not wait for an embassy appointment.',
  missions: MALAYSIA_EMBASSY_MISSIONS,
};
