import { NEARBY_AREAS, type MalaysiaPlaceSeedRecord, type MalaysiaPlacesSeed } from './types.js';

const everyday = (openMinutes: number, closeMinutes: number) =>
  [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, openMinutes, closeMinutes }));

export const MALAYSIA_NEARBY_PLACES: MalaysiaPlaceSeedRecord[] = [
  {
    id: 'my-food-madam-kwan',
    name: 'Madam Kwan’s (Suria KLCC)',
    nearbyCategory: 'food',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Suria KLCC, Kuala Lumpur City Centre',
    description: 'Malaysian classics in the mall under the Petronas Towers. Halal; good with families.',
    latitude: 3.15795,
    longitude: 101.71205,
    hours: everyday(10 * 60, 22 * 60),
    halal: true,
    englishSpoken: true,
    badges: ['Halal', 'Kid Favorite'],
    priceBandMyr: 'RM 35–70',
    website: 'https://www.madamkwans.com.my/',
  },
  {
    id: 'my-food-suria-court',
    name: 'Suria KLCC food court',
    nearbyCategory: 'food',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Level 4, Suria KLCC',
    description: 'Air-conditioned trays of local and simple plates next to KLCC Park.',
    latitude: 3.1577,
    longitude: 101.7119,
    hours: everyday(10 * 60, 22 * 60),
    halal: true,
    englishSpoken: true,
    badges: ['Halal', 'Kid Favorite'],
    priceBandMyr: 'RM 15–35',
  },
  {
    id: 'my-food-jalan-alor',
    name: 'Jalan Alor',
    nearbyCategory: 'food',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'Bukit Bintang',
    address: 'Jalan Alor, Bukit Bintang',
    description: 'Night food street: satay, seafood, and hawker stalls. Cash helps; spice varies by stall.',
    latitude: 3.1466,
    longitude: 101.7099,
    hours: everyday(17 * 60, 26 * 60),
    halal: null,
    englishSpoken: false,
    badges: ['Night food street'],
    priceBandMyr: 'RM 15–40',
  },
  {
    id: 'my-food-mamak-klcc',
    name: 'Nasi Kandar Pelita (KLCC)',
    nearbyCategory: 'food',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Jalan Ampang, near KLCC',
    description: '24-hour mamak-style Indian-Muslim plates: roti, nasi kandar, teh tarik.',
    latitude: 3.1594,
    longitude: 101.7142,
    alwaysOpen: true,
    halal: true,
    englishSpoken: true,
    badges: ['Halal', 'Open late'],
    priceBandMyr: 'RM 8–25',
  },
  {
    id: 'my-attr-petronas',
    name: 'Petronas Twin Towers',
    nearbyCategory: 'attractions',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Kuala Lumpur City Centre',
    description: 'The defining KL skyline. Skybridge and deck tickets are sold by the official operator.',
    latitude: 3.15785,
    longitude: 101.71165,
    hours: everyday(9 * 60, 21 * 60),
    halal: null,
    englishSpoken: true,
    badges: ['Landmark'],
    phone: '+60 3-2331 8080',
    website: 'https://www.petronastwintowers.com.my/',
    bookingUrl: 'https://www.petronastwintowers.com.my/',
    bookingLabel: 'Book tickets',
    photos: [
      {
        url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Petronas%20Twin%20Towers%20(Kuala%20Lumpur).jpg?width=1280',
        license: 'CC BY-SA 4.0',
        attribution: 'Wikimedia Commons — Petronas Twin Towers (Kuala Lumpur)',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:Petronas_Twin_Towers_(Kuala_Lumpur).jpg',
      },
    ],
  },
  {
    id: 'my-attr-klcc-park',
    name: 'KLCC Park',
    nearbyCategory: 'attractions',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'KLCC Park, Jalan Pinang',
    description: 'Free park with playground, lake, and evening fountain views of the towers.',
    latitude: 3.1569,
    longitude: 101.7131,
    alwaysOpen: true,
    halal: null,
    englishSpoken: true,
    badges: ['Free', 'Family'],
    photos: [
      {
        url: 'https://commons.wikimedia.org/wiki/Special:FilePath/KLCC%20Park.jpg?width=1280',
        license: 'CC BY-SA 3.0',
        attribution: 'Wikimedia Commons — KLCC Park',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:KLCC_Park.jpg',
      },
    ],
  },
  {
    id: 'my-attr-batu-caves',
    name: 'Batu Caves',
    nearbyCategory: 'attractions',
    city: 'Gombak',
    country: 'MY',
    area: 'Batu Caves',
    address: 'Batu Caves, Selangor',
    description: 'Limestone caves and temple complex. Modest dress; 272 rainbow steps. Take KTM Komuter.',
    latitude: 3.2379,
    longitude: 101.684,
    hours: everyday(6 * 60, 21 * 60),
    halal: null,
    englishSpoken: true,
    badges: ['Must-see', 'Temple'],
    photos: [
      {
        url: 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Lord%20Murugan%20statue%20at%20Batu%20Caves.jpg?width=1280',
        license: 'CC BY-SA 3.0',
        attribution: 'Wikimedia Commons — Lord Murugan statue at Batu Caves',
        sourceUrl: 'https://commons.wikimedia.org/wiki/File:The_Lord_Murugan_statue_at_Batu_Caves.jpg',
      },
    ],
  },
  {
    id: 'my-attr-merdeka',
    name: 'Merdeka Square',
    nearbyCategory: 'attractions',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'Downtown',
    address: 'Dataran Merdeka',
    description: 'Colonial cricket green and flagpole; walkable with Central Market and Petaling Street.',
    latitude: 3.1478,
    longitude: 101.6936,
    alwaysOpen: true,
    halal: null,
    englishSpoken: true,
    badges: ['Heritage'],
  },
  {
    id: 'my-transit-klcc-lrt',
    name: 'KLCC LRT station',
    nearbyCategory: 'transport',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Kelana Jaya Line, Suria KLCC',
    description: 'Kelana Jaya Line stop under Suria KLCC. Tap Touch ’n Go; first car may be women-only.',
    latitude: 3.15845,
    longitude: 101.71355,
    hours: everyday(6 * 60, 23 * 60 + 30),
    englishSpoken: true,
    badges: ['Rapid KL'],
  },
  {
    id: 'my-transit-bb-mrt',
    name: 'Bukit Bintang MRT',
    nearbyCategory: 'transport',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'Bukit Bintang',
    address: 'Kajang Line, Bukit Bintang',
    description: 'Kajang Line stop for Pavilion / Jalan Alor. Last-mile walk or monorail interchange nearby.',
    latitude: 3.1467,
    longitude: 101.7113,
    hours: everyday(6 * 60, 23 * 60 + 30),
    englishSpoken: true,
    badges: ['Rapid KL'],
  },
  {
    id: 'my-transit-grab-klcc',
    name: 'Grab pickup (KLCC Park / Convention)',
    nearbyCategory: 'transport',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'KL Convention Centre / KLCC Park pin',
    description: 'Use the in-app pin at the convention centre or park edge. Confirm the plate; ignore touts.',
    latitude: 3.1562,
    longitude: 101.7128,
    alwaysOpen: true,
    englishSpoken: true,
    badges: ['E-hailing'],
  },
  {
    id: 'my-atm-maybank-klcc',
    name: 'Maybank ATM (Suria KLCC)',
    nearbyCategory: 'atm',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Concourse, Suria KLCC',
    description: 'Bank ATM. Choose MYR (no conversion / without DCC). Cover the keypad.',
    latitude: 3.15775,
    longitude: 101.71185,
    hours: everyday(10 * 60, 22 * 60),
    englishSpoken: true,
    badges: ['Bank ATM'],
  },
  {
    id: 'my-atm-guardian-fx',
    name: 'Guardian licensed money changer (Suria KLCC)',
    nearbyCategory: 'atm',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Suria KLCC',
    description: 'Licensed exchange next to the pharmacy. Compare the posted rate before a large sum.',
    latitude: 3.15755,
    longitude: 101.71255,
    hours: everyday(10 * 60, 22 * 60),
    englishSpoken: true,
    badges: ['Best FX Rates', 'Licensed'],
  },
  {
    id: 'my-pharm-guardian',
    name: 'Guardian Pharmacy (Suria KLCC)',
    nearbyCategory: 'pharmacy',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Suria KLCC',
    description: 'Chemist with English-speaking staff, toiletries, and a licensed money changer nearby.',
    latitude: 3.15758,
    longitude: 101.7125,
    hours: everyday(10 * 60, 22 * 60),
    englishSpoken: true,
    badges: ['English-speaking'],
  },
  {
    id: 'my-pharm-watsons',
    name: 'Watsons (Pavilion KL)',
    nearbyCategory: 'pharmacy',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'Bukit Bintang',
    address: 'Pavilion Kuala Lumpur',
    description: 'Pharmacy and personal care in Pavilion. English signage; mall hours.',
    latitude: 3.149,
    longitude: 101.7134,
    hours: everyday(10 * 60, 22 * 60),
    englishSpoken: true,
    badges: ['English-speaking'],
  },
  {
    id: 'my-conv-7eleven-klcc',
    name: '7-Eleven (Jalan Ampang / KLCC)',
    nearbyCategory: 'convenience',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Jalan Ampang, KLCC',
    description: 'Water, snacks, and prepaid top-up. Useful late-night when malls are closed.',
    latitude: 3.1591,
    longitude: 101.7139,
    alwaysOpen: true,
    englishSpoken: false,
    badges: ['Late night'],
  },
  {
    id: 'my-conv-kk-bb',
    name: 'KK Super Mart (Bukit Bintang)',
    nearbyCategory: 'convenience',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'Bukit Bintang',
    address: 'Bukit Bintang',
    description: 'Local convenience chain for water, SIM top-up, and late-night snacks.',
    latitude: 3.1472,
    longitude: 101.7104,
    alwaysOpen: true,
    englishSpoken: false,
    badges: ['Late night'],
  },
  {
    id: 'my-svc-matic',
    name: 'Malaysia Tourism Centre (MaTiC)',
    nearbyCategory: 'tourist_services',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Jalan Ampang',
    description: 'Official visitor centre: maps, cultural shows, and Tourism Malaysia desks. Not an SOS line.',
    latitude: 3.1608,
    longitude: 101.7068,
    hours: everyday(8 * 60, 22 * 60),
    englishSpoken: true,
    badges: ['Official'],
    website: 'https://www.matic.gov.my/',
  },
  {
    id: 'my-svc-suria-guest',
    name: 'Suria KLCC Guest Services',
    nearbyCategory: 'tourist_services',
    city: 'Kuala Lumpur',
    country: 'MY',
    area: 'KLCC',
    address: 'Suria KLCC, concourse',
    description: 'Mall information desk for directions, lost and found, and luggage questions inside Suria.',
    latitude: 3.1579,
    longitude: 101.7118,
    hours: everyday(10 * 60, 22 * 60),
    englishSpoken: true,
    badges: ['Info desk'],
    website: 'https://www.suriaklcc.com.my/',
  },
];

export const MALAYSIA_PLACES_SEED: MalaysiaPlacesSeed = {
  country: 'MY',
  destination: 'Malaysia',
  version: '2026-09-mvp',
  areas: NEARBY_AREAS,
  places: MALAYSIA_NEARBY_PLACES,
};
